FROM php:8.1-fpm

ARG UID
ARG USER=www-data
ARG NODE_VERSION=14

ENV NVM_DIR /root/.nvm

RUN usermod -u ${UID} $USER

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    vim \
    curl \
    libedit-dev \
    libicu-dev \
    libxml2-dev \
    libzip-dev \
    libpng-dev \
    libpq-dev \
    libonig-dev \
    git \
    zip \
    unzip \
    python3

RUN docker-php-ext-install -j$(nproc) \
    gd \
    mbstring \
    mysqli \
    pdo_mysql \
    zip \
    opcache

RUN pecl install xdebug  \
    && docker-php-ext-enable xdebug mysqli

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
    && echo "source $NVM_DIR/nvm.sh" >> ~/.bashrc \
    && /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION" \
    && /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g yarn"

